language: python
sudo: false
dist: bionic
python:
  - "3.7"

install:
  - python -m pip install pytest-cov codecov coveralls PyYAML

# tests
script:
  - python -m pytest -v --cov=minima

after_success:
- codecov
- coveralls
