language: python
sudo: false
dist: bionic

install:
- python3 -m ensurepip
- python3 -m pip install pytest-cov codecov coveralls

# tests
script:
- >
    python3 -m pytest -v

after_success:
- codecov
- coveralls
