language: python
sudo: false
dist: bionic
python:
  - "3.7"

install:
  - python -m pip install pytest-cov codecov python-coveralls PyYAML

# tests
script:
  - python -m pytest -v --cov=minima --cov-report term-missing

after_success:
- codecov
- coveralls
